### ISSUE TITLE
The rest of the domains for DNS update

### ISSUE THREAD

**Issue by rdthom** [flowsa/africanenda-holding#1]
The following domains to also point at the holding page:

africanenda.org
africanenda.info
africanenda.net
africanenda.co
africanenda.africa
africanenda.tv
africanenda.biz
africanenda.co.uk (2-year)

**Comment by vashenmn** [comment]
@rdthom are we redirect all to africanenda.org or just point all to the landing page?

**Comment by richardfrankza** [comment]
In 99.99% all cases we want a single domain and 301 redirects to it due to SEO and brand reasons.

**Comment by vashenmn** [comment]
Redirects added

**Comment by rdthom** [comment]
browser is throwing privacy error before it re-directs

got it on africanenda.info - i assume similar will happen for the rest

**Comment by richardfrankza** [comment]
looks good to me

```
$ curl -I africanenda.info

HTTP/1.1 308 Permanent Redirect
Connection: close
Location: https://africanenda.info/
Server: Caddy
Date: Wed, 07 Jul 2021 06:50:45 GMT

$ curl -I www.africanenda.info

HTTP/1.1 308 Permanent Redirect
Connection: close
Location: https://www.africanenda.info/
Server: Caddy
Date: Wed, 07 Jul 2021 06:51:05 GMT
```

**Comment by richardfrankza** [comment]
The first request in my service actually generates the cert, so may cause issues
https://redirector.flowsa.net/

**Comment by vashenmn** [comment]
All sorted now. @rdthom please confirm ?

**Comment by rdthom** [comment]
lookin' good!
